### ISSUE TITLE
Add slider images

### ISSUE THREAD

**Issue by brettfarley** [brettfarley/martinez#2]
![r_martinez0120](https://cloud.githubusercontent.com/assets/13319038/11118153/46059c66-8905-11e5-8800-e6e0d9e47834.jpeg)
![r_martinez0374](https://cloud.githubusercontent.com/assets/13319038/11118155/4bb37476-8905-11e5-96d2-c4f2c349b4b3.jpeg)
![r_martinez0183](https://cloud.githubusercontent.com/assets/13319038/11118159/4ef541dc-8905-11e5-9be7-467d24d2d8cb.jpeg)

**Comment by brettfarley** [comment]
Ignore that first image. It's the wrong orientation. Use this one.
![r_martinez0005](https://cloud.githubusercontent.com/assets/13319038/11118182/738260b6-8905-11e5-9711-a9805a207e04.jpeg)

**Comment by arish-ricom** [comment]
Done.
